### PR TITLE
Force linter to fail ci check

### PR DESCRIPTION
**Pull request by Aristarhys**
`exit 1` will will called only if first flake8 will fail and return non zero code from script block immediately

Before last command of script block was evaluated and second flake8 invocation was always returning 0 because of flag passed

### CODE REVIEW

**Review by snazzyfox — APPROVED** [review]
LGTM. @shahsmit14 this ok with you?

**Comment by shahsmit14** [comment]
> LGTM. @shahsmit14 this ok with you?

There are quite some warning generated by Lint, so will this addition cause them to fail right away? If ye, we will have to get those fixed. Might be another MR.

**Comment by Aristarhys** [comment]
@shahsmit14 the lint with exit has limit amout of checked errors selected due to  `--select` flag - currently it's returns 0 (exit code and literally console output due to `--count` if only you don't add something really breaking like syntax error
second one will spam with some warnings, correct

you can use `-q` or `--qq` to make output less verbose

**Comment by Aristarhys** [comment]
@snazzyfox removed version bump, rebased, commit email fixed

**Pull request merged**
