### PR TITLE
Remove unused pyramid web framework dependency

### PR DESCRIPTION
**Pull request by Aristarhys**
[Pyramid](https://pypi.org/project/pyramid/) is web framework and there is no source files using anything from it

### CODE REVIEW

**Comment by snazzyfox** [comment]
Good catch. @sayanchk @shahsmit14 any reason why we included it in the first place?

**Comment by snazzyfox** [comment]
@Aristarhys Thanks a ton for helping us tidy up our build pipeline! Could you undo the version bump in this PR? We'd love to get them in but it's probably best to release once all of the changes are in. We'll update our docs to reflect this for future reference.

**Comment by sayanchk** [comment]
@snazzyfox @Aristarhys We were using pyramid previously but not any more after adding our own optimization logic. That's a good catch and we should remove the dependency.

**Comment by Aristarhys** [comment]
@sayanchk any pointers how to improve this PR? Can it be approved? I fixed commit title to differ `pyramid-arima` and `pyramid`

**Review by sayanchk — APPROVED** [review]
The change looks good to me.

**Review by snazzyfox — APPROVED** [review]

**Pull request merged**
